"""ajout colonne offre_id

Revision ID: 34f4f026d5b1
Revises: 168012574cee
Create Date: 2025-10-15 15:59:17.878270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34f4f026d5b1'
down_revision: Union[str, Sequence[str], None] = '168012574cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_files_id'), table_name='cv_files')
    op.drop_table('cv_files')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_postes_id'), table_name='postes')
    op.drop_table('postes')
    op.drop_index(op.f('ix_payelements_id'), table_name='payelements')
    op.drop_table('payelements')
    op.drop_index(op.f('ix_paies_id'), table_name='paies')
    op.drop_table('paies')
    op.drop_index(op.f('ix_contrats_id'), table_name='contrats')
    op.drop_table('contrats')
    op.drop_table('offres')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_employes_id'), table_name='employes')
    op.drop_table('employes')
    op.drop_table('candidatures')
    op.drop_index(op.f('ix_dossiers_disciplinaires_id'), table_name='dossiers_disciplinaires')
    op.drop_table('dossiers_disciplinaires')
    op.drop_index(op.f('ix_paie_elements_id'), table_name='paie_elements')
    op.drop_table('paie_elements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paie_elements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mois', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('salaire_base', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_a_payer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], name=op.f('paie_elements_employe_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paie_elements_pkey'))
    )
    op.create_index(op.f('ix_paie_elements_id'), 'paie_elements', ['id'], unique=False)
    op.create_table('dossiers_disciplinaires',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_faute', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preuve_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sanction', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], name=op.f('dossiers_disciplinaires_employe_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dossiers_disciplinaires_pkey'))
    )
    op.create_index(op.f('ix_dossiers_disciplinaires_id'), 'dossiers_disciplinaires', ['id'], unique=False)
    op.create_table('candidatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('adresse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_naissance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('poste', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('disponibilite', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('salaire', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('type_contrat', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mobilite', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('autorisation', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('cv_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lettre_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diplomes_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_candidature', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=50), server_default=sa.text("'En attente'::character varying"), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('candidatures_pkey'))
    )
    op.create_table('employes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('prenom', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('cin', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_naissance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_entree', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('poste_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statut', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poste_id'], ['postes.id'], name='employes_poste_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employes_pkey'),
    sa.UniqueConstraint('email', name='employes_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_employes_id'), 'employes', ['id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('actif', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('utilisateurs_pkey'))
    )
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employees_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poste', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_embauche', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('departement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('offres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('offres_pkey'))
    )
    op.create_table('contrats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_contrat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_debut', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('contrats_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('contrats_pkey'))
    )
    op.create_index(op.f('ix_contrats_id'), 'contrats', ['id'], unique=False)
    op.create_table('paies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('montant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date_paie', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('paies_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paies_pkey'))
    )
    op.create_index(op.f('ix_paies_id'), 'paies', ['id'], unique=False)
    op.create_table('payelements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('brut', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('contributions_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employes.id'], name=op.f('payelements_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payelements_pkey'))
    )
    op.create_index(op.f('ix_payelements_id'), 'payelements', ['id'], unique=False)
    op.create_table('postes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('postes_pkey'))
    )
    op.create_index(op.f('ix_postes_id'), 'postes', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contenu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('cv_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_files_pkey'))
    )
    op.create_index(op.f('ix_cv_files_id'), 'cv_files', ['id'], unique=False)
    # ### end Alembic commands ###
